name: Build OBJ file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: karcherm/action-install-jw@v1.0
        with:
          jwasm: true
      - name: Assemble the patch
        run: |
          jwasm -Zm -Fo274x-211.obj 274x-211.asm
          jwasm -Zm -Fo284x-101.obj 284x-101.asm
      - uses: actions/upload-artifact@v2
        with:
          name: scsi_edd
          path: |
            274x-211.obj
            284x-101.obj
            bios16k.map
            bios1632.map
